name: Notificar Push a NTFY

on:
  push:
    branches:
      - main
      - master

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Title: 🚨 Push Detectado" \
               -H "Priority: 4" \
               -H "Tags: github,rocket" \
               -d "Se ha hecho push a ${{ github.ref_name }} en el repo ${{ github.repository }} por el usuario ${{ github.actor }} 🚀" \
               https://ntfy.sh/devops-itla