- name: Enviar notificación personalizada
  run: |
    REPO="AdrielApX/Integracion_Continua_Electiva2"
    BRANCH=${GITHUB_REF##*/}
    ACTOR=${{ github.actor }}
    
    curl -H "Title: Push realizado" \
         -H "Priority: 4" \
         -H "Tags: rocket,devops" \
         -H "Content-Type: text/plain" \
         -d "Se ha hecho push a ${BRANCH} en el repo ${REPO} por el usuario ${ACTOR} 🚀" \
         https://ntfy.sh/devops-itla